import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TopNav from '../components/TopNav'
import Router from 'next/router'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TopNav /> */}
      <div className="relative flex flex-col justify-center min-h-screen overflow-hidden">
        <div className="w-full p-6 m-auto bg-[#1a1e27] text-white rounded-md shadow-md lg:max-w-xl">
          <h1 className="text-3xl font-semibold text-center text-[#0284c7]">
            Sign in
          </h1>
          <div className="flex justify-center items-center mt-5">
            <button
              onClick={() => {
                Router.push("/home")
              }
              }
              className="bg-sky-500 text-white rounded-md shadow-md p-2 mt-5 w-1/2 flex items-center justify-center"
            >
              Connect
            </button>
          </div>

          <p className="mt-8 text-xs font-light text-center text-white">
            {" "}
            Don&apos;t have an account?{" "}
            <a href="#" className="font-medium text-[#0284c7] hover:underline">
              Sign up
            </a>
          </p>
        </div>
      </div>
    </>
  )
}
