import React from "react";
import Router from "next/router";
import Head from "next/head";
import Web3Modal, { providers } from "web3modal";
import { ethers } from "ethers";
// import * as PushAPI from "@pushprotocol/restapi";
import { useAuth } from "@arcana/auth-react";
import { rpcURLnetwork, authArcana } from "../utils/authArcana";

export default function Login() {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const auth = useAuth();
  const { user, connect, isLoggedIn, loading, loginWithSocial, provider } =
    useAuth();
  const onConnectClick = async () => {
    try {
      await connect();
    } catch (e) {
      console.log(e);
    }
  };
  const onConnect = async () => {
    console.log("connected");
    await authArcana.init();
    Router.push("/home");
  };
  React.useEffect(() => {
    provider.on("connect", onConnect);
    return () => {
      provider.removeListener("connect", onConnect);
    };

  }, [provider]);
  // TODO: Integrate Arcana Login
  return (
    <>
      <Head>
        <title>ICC App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative flex flex-col justify-center min-h-screen overflow-hidden">
        <div className="w-full p-6 m-auto bg-[#1a1e27] text-white rounded-md shadow-md lg:max-w-xl">
          <h1 className="text-3xl font-semibold text-center text-[#0284c7]">
            Sign in
          </h1>
          <div className="flex justify-center items-center mt-5">
            <button
              onClick={onConnectClick}
              className="bg-sky-500 text-white rounded-md shadow-md p-2 mt-5 w-1/2 flex items-center justify-center"
            >
              Connect
            </button>
          </div>

          <p className="mt-8 text-xs font-light text-center text-white">
            {" "}
            Don&apos;t have an account?{" "}
            <a href="#" className="font-medium text-[#0284c7] hover:underline">
              Sign up
            </a>
          </p>
        </div>
      </div>
    </>
  );
}